# Generated by Django 2.2.9 on 2020-05-22 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_app', '0006_auto_20200517_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 7, 56, 16, 675109, tzinfo=utc)),
        ),
    ]
