# Generated by Django 3.0.5 on 2020-05-11 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_post', '0004_auto_20200509_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 5, 22, 46, 943352, tzinfo=utc)),
        ),
    ]
